//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantHireOrderItem
    {
        public int itemOrderID { get; set; }
        public Nullable<int> orderNumberID { get; set; }
        public Nullable<int> item { get; set; }
        public string quantity { get; set; }
        public string unit { get; set; }
        public string description { get; set; }
        public Nullable<decimal> weeklyrate { get; set; }
        public Nullable<float> discount { get; set; }
        public Nullable<int> hireCost { get; set; }
        public Nullable<System.DateTime> dateRequiredOnSite { get; set; }
        public string duration { get; set; }
        public string offHiredNo { get; set; }
        public Nullable<System.DateTime> offHireDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual plantHireOrder plantHireOrder { get; set; }
    }
}
