//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantHireOrder
    {
        public int orderNumberID { get; set; }
        public Nullable<int> projectID { get; set; }
        public string vendorLocationID { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> quantity { get; set; }
        public string unit { get; set; }
        public string Description { get; set; }
        public Nullable<int> weeklyRate { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> hireCost { get; set; }
        public Nullable<System.DateTime> dateRequiredOnSite { get; set; }
        public string duration { get; set; }
        public string offHireNo { get; set; }
        public Nullable<System.DateTime> offHireDate { get; set; }
    }
}
