//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantHireOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plantHireOrder()
        {
            this.plantHireOrderItems = new HashSet<plantHireOrderItem>();
        }
    
        public int orderNumberID { get; set; }
        public Nullable<int> projectID { get; set; }
        public string title { get; set; }
        public string vendorLocationID { get; set; }
        public Nullable<System.DateTime> dateRequiredOnSite { get; set; }
        public string duration { get; set; }
        public string offHireNo { get; set; }
        public string siteContact { get; set; }
        public string originator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plantHireOrderItem> plantHireOrderItems { get; set; }
        public virtual project project { get; set; }
    }
}
