//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectRequisition
    {
        public int projectRequisitionID { get; set; }
        public int projectID { get; set; }
        public Nullable<int> requisitionID { get; set; }
        public string itemCodeID { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public Nullable<bool> deliveryRestrictions { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual project project { get; set; }
        public virtual requisition requisition { get; set; }
    }
}
