//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requisition()
        {
            this.projectRequisitions = new HashSet<projectRequisition>();
        }
    
        public int requisitionID { get; set; }
        public string title { get; set; }
        public string itemNo { get; set; }
        public string description { get; set; }
        public string quantity { get; set; }
        public Nullable<System.DateTime> dateRequired { get; set; }
        public string deliverTo { get; set; }
        public string itemCodeID { get; set; }
        public Nullable<System.DateTime> requisitionDate { get; set; }
    
        public virtual itemContent itemContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectRequisition> projectRequisitions { get; set; }
    }
}
