//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorHQTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendorHQTable()
        {
            this.vendorLocationDetails = new HashSet<vendorLocationDetail>();
        }
    
        public string vendorID { get; set; }
        public string vendorLocationID { get; set; }
        public string vendorAddress1 { get; set; }
        public string vendorAddress2 { get; set; }
        public string vendorCity { get; set; }
        public string vendorCounty { get; set; }
        public string vendorPostCode { get; set; }
        public string vendorPhoneNumber { get; set; }
        public string vendorContact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendorLocationDetail> vendorLocationDetails { get; set; }
    }
}
